### PR TITLE
experiment to try and fix 

### PR DESCRIPTION
**Pull request by chrisns**

### CODE REVIEW

**Comment by robertsLando** [comment]
@chrisns I know that feel, when github action keeps fail :rofl: Remember the dynamic matrix was a pain like this for a stupid problem

**Comment by chrisns** [comment]
setup act on my machine now so can at least reproduce locally
theres some weird problems with multi-line params being passed between actions, am looking into it

**Comment by robertsLando** [comment]
@chrisns Do you have the comma separeted solution?

**Comment by robertsLando** [comment]
@chrisns Ignore my comment I just saw the commits in master, missed them :) 

Thanks @chrisns ! :smiley:  We will get the Hacktober fest t-shirt :rofl:

**Pull request closed without merging**
