### PR TITLE
chore(docker): stable builds and refactor

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by robertsLando** [comment]
@chrisns Build is failing because your image is still not available yet

**Comment by chrisns** [comment]
sorry that was a long breakfast! fixed the build

**Comment by robertsLando** [comment]
@chrisns No worries, it's working now :tada:

**Comment by robertsLando** [comment]
@chrisns Review than I can merge this

**Comment by robertsLando** [comment]
@chrisns Thanks mate :pray:

**Pull request merged**
