### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dbaker-rh**
Fix URL for kustomization.yaml

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]
LGTM. Thanks @dbaker-rh

**Comment by robertsLando** [comment]
@chrisns Is the docker build still failing?

**Comment by chrisns** [comment]
worked here, might be broken for prs from forks? will look at it

**Comment by robertsLando** [comment]
@chrisns I think it's broken for PRs. `No matching manifest for platform`

**Comment by chrisns** [comment]
yeah, merge this pr, since it obviously wouldn't be causing the issue, i'll fork and raise a pr to work through fixing

**Comment by chrisns** [comment]
actually, its just broken.
node have stopped pushing `linux/386` builds to dockerhub will raise pr to remove that

**Review by chrisns — APPROVED** [review]

**Pull request merged**
