### PR TITLE
[WIP] Added network graph 

### PR DESCRIPTION
**Pull request by mlankamp**
I've started with a network graph for the vuejs front-end (very simple so far):
image

Would love to receive feedback!

### CODE REVIEW

**Comment by robertsLando** [comment]
This was In my Todo List! Thanks will review this on Monday :) 

Daniel

**Comment by robertsLando** [comment]
Hi @mlankamp. Thanks for your PR! What about create a method on zwaveclient "refreshNeightburns" that foreach node in network updates the neightburns? This method should be called on scan complete and when a node is available and the scan is complete (like for groups). Also I'm thinking about moving all the api stuff in app.vue or maybe moving this to control panel in a tab because there is too much repeating code (I mean for the socket management)

**Comment by mlankamp** [comment]
I think it's a good idea to move the socket code to app.vue and store all information about the nodes in vuex. 
The scan complete method is called in the server or client?

**Comment by robertsLando** [comment]
Are you able to do this? I mean move the socket code to app.vue and add nodes to vuex? Vuex is already set for settings but not for nodes. Actually I’m a lit busy so if you want to implement this it is more than welcome. About the scan complete, there is an event in ZwaveClient.js “onScanComplete”. Also there is a function called “initNode” that is used to init a node, at the end of this function there is a check “if(this.scanComplete)” that is used to update groups when a node is added “on fly” while gateway is running. I suggest to handle neighbors like groups so update them on scun complete and here in initNode function if scan is complete and then create a finction “refreshNeightbourns” that refresh all nodes neighbors and add them to the node property “neightburns”, this function could also be called from the mesh graph UI with a button used to update the graph. Then I also plan to add some more feature in graph but this is enough for now :) if you need help write a privste message on slack channel and I will give you support for this! Once I have more time I will help you with code too if needed. Thanks

Daniel

**Comment by mlankamp** [comment]
Hi Daniel,

I can move the code to app.vue, no problem. Can I change the source to use Typescript? I use vuejs a lot in combination with typescript, and vuejs 3+ will be typescript based.

Michiel

**Comment by robertsLando** [comment]
Check 2a6c4fc71433c770d58bd39e05b3359582592acd and 3eafd996381ff0b27a20c0182a31305a9c68d690

Now neighborns are automatically refreshed on zwave client when nodes are added, just call the api `refreshNeighborns` to update all them. It doesn't return anything

**Comment by robertsLando** [comment]
@mlankamp Nice! If you want and you have time to do it would be wonderful to make it typescript based

**Comment by robertsLando** [comment]
@mlankamp I have updated the `refreshNeighburns` in 72441c6eb5e92b821e82066abc57fae755fa8656 to return the updated ndoes neighburns so now when you send the api request you will get all neightburns in the response :)

**Comment by mlankamp** [comment]
I've started converting the solution to typescript. The backend is almost ready, the frontend is next.

**Comment by robertsLando** [comment]
Perfect! Thanks :) I will add a section on readme with your name and other special contributors :) 

Daniel

**Comment by robertsLando** [comment]
@mlankamp  I have added you to the [thanks](https://github.com/OpenZWave/Zwave2Mqtt/#-thanks) section of the project :)

**Comment by robertsLando** [comment]
@mlankamp Any news about this?

**Comment by mlankamp** [comment]
I'm currently on holiday, will proceed next week.

**Comment by RualdOrdelman** [comment]
This would be a great add-on. Waiting for a long time for this kind of functionality.

**Comment by robertsLando** [comment]
@RualdOrdelman I'm waiting for @mlankamp to end its convertion to typescript, I could accept this pr for now than wait him to end with other things

**Comment by robertsLando** [comment]
@RualdOrdelman @thundergreen Closed in favor of 5c73aa4b94eea29d2cea03a5be623a3093d1d0f9

**Pull request closed without merging**
