### PR TITLE
quiet down custom-devices-related logs

### LINKED ISSUE #686: [bug] Logs are flooded with `z2m:Gateway no custom devices sources found`
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt docker: 4.0.2

**Describe the bug**
Logs are being flooded with:
```
z2m     | 2020-08-24 10:20:02.717 Detail, Node002,   Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
z2m     | 2020-08-24 10:20:02.718 Detail, Node002,   ZW_SEND_DATA delivered to Z-Wave stack
z2m     |   z2m:Gateway no custom devices sources found +4ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +6ms
z2m     | 2020-08-24 10:20:02.835 Detail, Node002,   Received: 0x01, 0x07, 0x00, 0x13, 0x53, 0x00, 0x00, 0x0d, 0xb5
z2m     | 2020-08-24 10:20:02.835 Detail, Node002,   ZW_SEND_DATA Request with callback ID 0x53 received (expected 0x53)
```

**To Reproduce**
1. Start the container and observe the logs

**Expected behavior**
Either to not flood the logs or not check for customDevices every few milliseconds!

**Additional context**
This may be related to changes introduced by #670, #675, and #679

### PR DESCRIPTION
**Pull request by pdbogen**
1. if directory watch gets filename field and it _isn't_ a file we want, ignore the event
2. don't log "no custom devices sources found"

Tested by:

* `touch`ing an arbitrary file `store/test` and observing no log message emitted (in fact, this was _before_ log line was removed, to be sure)
* `touch store/customDevices.js` & observe `Loaded 0 custom Hass devices configurations`, so still loading in general
* `rm store/customDevices.js; echo '{}' > store/customDevices.json` & observe no log message, because there's no change to customDevices config (empty .js & `{}` JSON are the same content)
* `echo '{ "test": "test" }' > store/customDevices.json` & observe one custom config loaded

On my system, where `fs.watch` reliable provides `filename`, with this change there are _no_ syscalls made when a file other than customDevices is modified.

I checked this (a) when neither file exists; (b) when `customDevices.js` exists; (c) when `customDevices.json` exists; and (d) when both files exist.

This fixes #686.

### CODE REVIEW

**Comment by pdbogen** [comment]
n.b., nodejs docs say:

> filename argument in the callback is only supported on Linux, macOS, Windows, and AIX. Even on supported platforms, filename is not always guaranteed to be provided

No information is given about when filename might not be provided on a supported platform. I guess zwave2mqtt is probably not supported on any _other_ platforms. I expect this means that _for the most part_ this will reduce excess syscalls to zero.

**Comment by robertsLando** [comment]
>  I guess zwave2mqtt is probably not supported on any other platforms

It could but in 99% of cases it is used on linux/docker linux containers

**Comment by pdbogen** [comment]
Ya. And even then, I guess the only unsupported platforms are, like... nodeMCU, android, iOS ... I don't see anyone running z2m on those.

**Review by robertsLando — APPROVED** [review]
LGTM

**Comment by pdbogen** [comment]
@robertsLando if we're ready to merge, mind doing so?

**Comment by robertsLando** [comment]
@pdbogen Sorry but I was from my phone and I prefer to better check on my pc, also having some busy days at work. Thanks for the quick fix, submitting a patch release asap

**Pull request merged**
