### PR TITLE
fix: set temperature_unit in climate discovery #731

### PR DESCRIPTION
**Pull request by robertsLando**
@chilicheech Check out this please

### CODE REVIEW

**Comment by chilicheech** [comment]
Ah, yes, this looks good. I forgot that we have the `unit` field that we can use. That's why I was thinking of using `49-1-256`, but you're right, not every device has that.

Code looks good. I'm gonna test it on my setup. I'll do it as soon as I can. But don't wait for me to merge this.

**Comment by chilicheech** [comment]
bah.. spoke too soon:
```
z2m     |   z2m:Gateway Error while discovering device climate_thermostat of node 31: currTemp.units.contains is not a function +0ms
```

**Comment by chilicheech** [comment]
In my tests I replaced `contains` with `includes` and it worked:
I replaced `payload.temperature_unit = currTemp.units.contains('C') ? 'C' : 'F'`
with `payload.temperature_unit = currTemp.units.includes('C') ? 'C' : 'F'`

**Comment by robertsLando** [comment]
Could you send a PR? Or I will do it tomorrow, not on my laptop right now :)

**Comment by chilicheech** [comment]
Here's the PR #733 
https://github.com/OpenZWave/Zwave2Mqtt/pull/733
Cheers

**Comment by robertsLando** [comment]
Thanks @chilicheech !

**Pull request merged**
