### PR TITLE
test coverage lib/debug

### PR DESCRIPTION
**Pull request by chrisns**

### CODE REVIEW

**Comment by robertsLando** [comment]
Essentially if DEBUG env is set I don’t automatically enable the debug module. Because without that instruction (debug.enable) you would not see any log in stdout/stderr, you should always specify the env var when starting z2m. 

We could think about move to pinojs logger for logging 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by robertsLando** [comment]
The test so could just listen to stdout/err data event when that env var is set or not

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chrisns** [comment]
Don’t want to test a third party module.
Just couldn’t spot on the debug obj what changed to be able to test it. Might just mock the external code with proxyquire

**Comment by robertsLando** [comment]
@chrisns Nothing changes, the only thing that changes is the one I told you (stderr/stdout should or should not receive data).

**Comment by robertsLando** [comment]
@chrisns Maybe this could help: https://github.com/visionmedia/debug/blob/master/src/common.js#L156

**Comment by chrisns** [comment]
@robertsLando this is ready to review now if you have a mo, thanks

**Comment by robertsLando** [comment]
Will look at it tomorrow, thanks Chris 🙏🏻 

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Pull request merged**
