### PR TITLE
close stale issues+prs

### PR DESCRIPTION
**Pull request by chrisns**
attempt to tidy up the backlog of issues+prs and make sure they're still relevant.
hopefully the text reads friendly enough, suggest we try at 30 and see if we need to increase the days if it's more annoying than useful

adding `no-stale` label will prevent it applying to any of the longer term features/prs etc

### CODE REVIEW

**Comment by robertsLando** [comment]
I'm not sure to want this, I see lot repos use this stale bot but sometimes it closes something it should be keep opened. I think some of the issues opened could be closed but 90% of them should be kept opened. I mean mostly are feature request that I'm waiting to find some time to implement them

**Comment by chrisns** [comment]
was just trying to tidy up the loose ends after i was going through manually trying to close tickets that looked old and irrelevant, figured a bot doing it instead of me might look a little less harsh and people might be more comfortable to reopen than if a human closed it?

30 days is probably a bit ambitious given the small community of contributors.

**Comment by robertsLando** [comment]
> 30 days is probably a bit ambitious given the small community of contributors.

That's the problem, I have some issues in my todo list but sincery I have no idea if and when I will do them, also when in other repos I see that they use this bot IMO it's annoying to see your issue closed just because the developer 'forgot' your issue

**Comment by chrisns** [comment]
set to 90 days?
can ignore stuff you've labelled as 'todo'
the point is to try and reduce and make you/us revalidate the 'if' point.

I'd put forward that the developer forgetting the issue is the main annoyance, this sends out a reminder 5 days prior to closing so everyone has an opportunity to 'bump' it to remain current, its not a hard cut off

**Comment by robertsLando** [comment]
> set to 90 days? can ignore stuff you've labelled as 'todo'

Ok set it to 90 days and ignore the 'feature request' labels

**Comment by chrisns** [comment]
> > set to 90 days? can ignore stuff you've labelled as 'todo'
> 
> Ok set it to 90 days and ignore the 'enhancment' labels

👍

**Review by robertsLando — APPROVED** [review]
Lgtm

**Pull request merged**
