### PR TITLE
fix: change default hass birth/will topic

### LINKED ISSUE #638: Home Assistant 0.113 change to birth and will message topic defaults
**Describe the solution you'd like**
Per the Home Assistant 0.113 release notes, they have changed the MQTT integration to have a default topic for birth and will messages of "homeassistant/status". Details can be found in release notes at: https://www.home-assistant.io/blog/2020/07/22/release-113/

It would be ideal if Zwave2Mqtt either made the topic configurable, or if it would be updated to use the default value from HA. With HA going more and more towards UI based configuration, having to manually update the configuration YAML should ideally be an option, but not a requirement.

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #638

BREAKING CHANGE: Default Hass Birth/Will topic is changed from `hass/status` to `homeassistant/status` to reflect defaults of Hass 0.113

### CODE REVIEW

**Comment by chrisns** [comment]
not read all the code, does this still use the topic prefix?

**Comment by robertsLando** [comment]
> does this still use the topic prefix

Nope, it's a fixed topic :)

**Comment by chrisns** [comment]
that seems like a bad thing, maybe my use case is unique but i run three zwave networks, one usa, one eu and another for another location. I don't run HA but if I did i'd probably want to separate the messages?

**Comment by robertsLando** [comment]
@chrisns Nope, If you have 3 zwave network that are using the same broker and are publishing values all to the same hass instance it is correct, when the hass instance restarts all the 3 z2m instances will be notified about this. 

It's just a birth/will topic, it means that hass will publish there a message when it starts and when it stops.

**Comment by chrisns** [comment]
ah ok, fine, but multiple HASS would be a problem then sharing the broker?

**Comment by robertsLando** [comment]
I don't know why someone should do such thing but yes, in that case could be a problem (not really a big one, just when one has instance goes down even the other one will receive a rediscovery of the components, nothing that breaks anything it's just useless)

**Comment by robertsLando** [comment]
@chrisns Waiting for that user asking for that feat :rofl: In that case I will make that option configurable

**Comment by chrisns** [comment]
heh, i'd considered doing it when i pondered setting hass up :)

**Comment by robertsLando** [comment]
Why don't use 2 different brokers?

**Comment by robertsLando** [comment]
If you are interested I could make the support for this, just because it's you 😂

**Comment by chrisns** [comment]
ha, hold fire until i try again to use HA

**Comment by raetha** [comment]
As the original requester, to add my two cents. I'm now using the HA UI to configure my MQTT broker, in that scenario HA uses the default values suggested here. However, as far as I know you can still configure MQTT via YAML in HA and set alternate options for the birth and will messages. So though I'm only interested in the default, I could absolutely see others interested in having it configurable, since HA still allows that. But who knows for how much longer HA will allow it, as they slowly deprecate many things from YAML in favor of UI.

I also agree that having two HA instances point to one MQTT instance is likely to cause nothing but confusion or problems, but this being configurable would technically allow multiple Z2M and HA instances on the same MQTT broker.

**Comment by robertsLando** [comment]
I absolutely agree @raetha, I just would like to keep configuration minimal to don't create any confusion, I have removed many other config in zwave for example because users don't like to read readme :confused: So I'm waiting for that user asking for this to see if it's really usefull or not

**Pull request merged**
