### PR TITLE
fix: implement more environment variables for configuration

### PR DESCRIPTION
**Pull request by onedr0p**
Allows more zwave settings to be declared via environment variables

- `OZW_SAVE_CONFIG`
- `OZW_POLL_INTERVAL`
- `OZW_AUTO_UPDATE_CONFIG`
- `OZW_CONFIG_PATH`
- `OZW_ASSUME_AWAKE`

### CODE REVIEW

**Comment by onedr0p** [comment]
Not sure what the issue is in the CI

**Comment by onedr0p** [comment]
I am having some lovely issues with node and gyp. I'll try again later.

image

**Review by robertsLando — CHANGES_REQUESTED** [review]
Could you add docs about env vars please? 

Add a section on readme named `Environment variables`

**Comment by onedr0p** [comment]
Envar section added 👍

**Review by robertsLando — APPROVED** [review]
LGTM

**Pull request merged**
