### PR TITLE
chore: major deps bump, code refactor and dark mode

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by robertsLando** [comment]
@chrisns  FInally I have been able to make the projet webpack 4 compatible. Please review this wehn you have time. 

Now I need to update UI

**Comment by chrisns** [comment]
looks ok, apart from all the new linting errors the newer eslint throws up :)

**Comment by robertsLando** [comment]
@chrisns This is ready for the review. I suggest you to checkut on this branch and make some tests manually on the ui to check everything is working good

The only thing I'm not able to fix right now is to get the 'Value updated' notification, seems that vue has changed something on low level and not all values are passed by reference but some are cloned

**Comment by robertsLando** [comment]
@chrisns I'm not able to reproduce your issue.

Are you using `npm run dev` command and going to localhost:8092?

**Comment by chrisns** [comment]
npm run build
npm start

**Comment by robertsLando** [comment]
@chrisns Try to check it now, I have added a check

**Comment by chrisns** [comment]
ace, will carry on testing and reading code

**Comment by chrisns** [comment]
looks about right loving the dark mode 🕶️

**Comment by robertsLando** [comment]
Let's wait that https://github.com/robertsLando/Zwave2Mqtt-docker/runs/646219315 ends then we can merge this

**Pull request merged**
