### PR TITLE
docs: add depencencies security/status badges

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by robertsLando** [comment]
Interesting :heart_eyes:

**Comment by robertsLando** [comment]
@chrisns Do you suggest make the LGTM check required in order to allow merge?

**Comment by chrisns** [comment]
> @chrisns Do you suggest make the LGTM check required in order to allow merge?
maybe, i'd leave it in passive mode for the minute, see if it likes our code :)

**Comment by chrisns** [comment]
...maybe when we feel confident enough to also make `coverage/coveralls` required? :)

**Pull request merged**
